#!/usr/bin/env python3

import os
import re
from statistics import mean, median, stdev
import sys

def pp(x):
    return re.sub(r'(\.\d*[^0])0+$|\.0+$', r'\1', str(x))

try:
    vals = []
    for line in sys.stdin:
        vals.extend([float(v) for v in line.split()])
except ValueError as e:
    print(f'error: {e}', file=sys.stderr)
    sys.exit(1)

if not vals:
    print(f'error: no input', file=sys.stderr)
    sys.exit(1)

ops = {'n': len, 'min': min, 'max': max, 'sum': sum,
        'mean': mean, 'median': median, 'stdev': stdev}
for name, op in ops.items():
    print(f'{name:<6} = {pp(op(vals))}')
